package com.sample

import java.util.List;
import java.util.Map;
import java.util.Date;

declare Article
  name: String
  tag: int
  updateTime: Date
end

declare Customer
  id: long @key
  firstName : String
  lastName : String
  age : int
  birthDay : Date
  subscriptions: List
  sponsors: Map
end

declare Subscription
  id: long @key
  label: String
  channel: String
  timeStamp: Date
end

declare LocalVariables
  propensity: double
  isEligiable: boolean
  subscription : Subscription
  channel: String
end

global List articles;
global Customer customer;

rule "Customer eligibility"
dialect "mvel"
    when
    then
    	LocalVariables lv = new LocalVariables();
    	lv.isEligiable = customer.age > 18;
    	lv.propensity = 0.87;
    	lv.subscription = customer.subscriptions[2];
    	lv.channel = lv.subscription.channel;
    	insert(lv);
    	$n = customer.lastName + " " + customer.firstName;
        System.out.println("pick an article for the customer " + $n);
        System.out.println("the subscription he had was from " + lv.channel);
end

rule "Pick article"
	when 
	   LocalVariables( $e : isEligiable, $p : propensity)
   	   $a : Article(tag == 1, $e, $p > 0.5) from articles
   	then
       System.out.println( "The recommended article is " + $a.getName());
end